name: Build and Push Docker image

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Docker tags
        id: docker_tags
        run: |
          TAGS="${{ secrets.DOCKERHUB_USERNAME }}/collector:latest\n${{ secrets.DOCKERHUB_USERNAME }}/collector:${GITHUB_SHA::7}"
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAGS="$TAGS\n${{ secrets.DOCKERHUB_USERNAME }}/collector:${GITHUB_REF#refs/tags/}"
          fi
          echo -e "TAGS<<EOF\n$TAGS\nEOF" >> $GITHUB_ENV
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.TAGS }}
